{"name": "test_add_with_type_error[1-1-2]", "status": "passed", "parameters": [{"name": "x", "value": "1"}, {"name": "y", "value": "'1'"}, {"name": "res", "value": "2"}], "start": 1714731955151, "stop": 1714731955151, "uuid": "9bce93a1-6935-47b3-9c80-7d7c5f89c144", "historyId": "7bfcf4987460dd7ad05408552bbe17e3", "testCaseId": "c4535174573fa79997bd065240c66b58", "fullName": "tests.tests_2024.test_main.TestCalculator#test_add_with_type_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('fixture_one', 'fixture_two')"}, {"name": "parentSuite", "value": "tests.tests_2024"}, {"name": "suite", "value": "test_main"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "acernb001"}, {"name": "thread", "value": "26963-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_2024.test_main"}]}