{"name": "test_failed_two_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failed_two_three():\n>       assert False\nE       assert False\n\ntests/hooks_example_three/test_hooks_three.py:9: AssertionError"}, "start": 1708622330433, "stop": 1708622330433, "uuid": "6c2920ec-9f84-4366-84e6-f86a4cf2929b", "historyId": "50a44c239c112337e9c25479b8e3e667", "testCaseId": "ab8ed8b03d8ae69dbc6b148af1f0d44b", "fullName": "tests.hooks_example_three.test_hooks_three#test_failed_two_three", "labels": [{"name": "parentSuite", "value": "tests.hooks_example_three"}, {"name": "suite", "value": "test_hooks_three"}, {"name": "host", "value": "Macbook-Pro-Flora.local"}, {"name": "thread", "value": "21814-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.hooks_example_three.test_hooks_three"}]}