{"name": "test_failed", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_failed():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests/something/test_something.py:79: AssertionError"}, "start": 1708622134661, "stop": 1708622134661, "uuid": "45d1745a-27a6-4c2b-8167-6fbc4589143f", "historyId": "443dd7304257a1ce4f463c620a9eb01d", "testCaseId": "9ec33ceeb4b06143f45a574f5db5008f", "fullName": "tests.something.test_something#test_failed", "labels": [{"name": "parentSuite", "value": "tests.something"}, {"name": "suite", "value": "test_something"}, {"name": "host", "value": "Macbook-Pro-Flora.local"}, {"name": "thread", "value": "21607-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.something.test_something"}]}