{"uuid": "69c0f1c6-637a-4f3d-81b5-6501e9bca995", "children": ["23ff7d79-e100-46a3-a041-67ea35b5ff96"], "befores": [{"name": "generate_item_type", "status": "broken", "statusDetails": {"message": "sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column \"item_id\" violates not-null constraint\nDETAIL:  Failing row contains (null, manager).\n\n[SQL: INSERT INTO item_type (item_type) VALUES (%(item_type)s) RETURNING item_type.item_id]\n[parameters: {'item_type': 'manager'}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)\n", "trace": "  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/fisher/PycharmProjects/pytest_2023/tests/conftest.py\", line 100, in generate_item_type\n    get_add_method(get_db_session, item)\n  File \"/home/fisher/PycharmProjects/pytest_2023/tests/conftest.py\", line 69, in add_method\n    session.commit()\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py\", line 1969, in commit\n    trans.commit(_to_root=True)\n  File \"<string>\", line 2, in commit\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py\", line 1256, in commit\n    self._prepare_impl()\n  File \"<string>\", line 2, in _prepare_impl\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py\", line 1231, in _prepare_impl\n    self.session.flush()\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py\", line 4312, in flush\n    self._flush(objects)\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py\", line 4447, in _flush\n    with util.safe_reraise():\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py\", line 4408, in _flush\n    flush_context.execute()\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py\", line 466, in execute\n    rec.execute(self)\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py\", line 642, in execute\n    util.preloaded.orm_persistence.save_obj(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py\", line 93, in save_obj\n    _emit_insert_statements(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py\", line 1227, in _emit_insert_statements\n    result = connection.execute(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 1416, in execute\n    return meth(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py\", line 517, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 2344, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"/home/fisher/PycharmProjects/pytest_2023/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n"}, "start": 1709643072579, "stop": 1709643073470}], "start": 1709643072579, "stop": 1709643074220}