{"name": "test_failed_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failed_two():\n>       assert False\nE       assert False\n\ntests/hooks_example_two/test_hooks_two.py:10: AssertionError"}, "start": 1709643071359, "stop": 1709643071360, "uuid": "ab45c8e3-f83f-462f-8b61-b2b82708525f", "historyId": "f06e2a9e3dd12432c135ff9ce70a8cd6", "testCaseId": "6d40bfc4e1d11b93f29dc3326bfbe44b", "fullName": "tests.hooks_example_two.test_hooks_two#test_failed_two", "labels": [{"name": "parentSuite", "value": "tests.hooks_example_two"}, {"name": "suite", "value": "test_hooks_two"}, {"name": "host", "value": "fisher-P55A-UD3"}, {"name": "thread", "value": "38528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.hooks_example_two.test_hooks_two"}]}