{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23414] Issue with network connection", "trace": "('/home/user/PycharmProjects/pytest_2023/tests/users/test_users.py', 22, 'Skipped: [ISSUE-23414] Issue with network connection')"}, "start": 1678120236387, "stop": 1678120236387, "uuid": "646d30e7-4a9f-4ea7-813b-13df1de22907", "historyId": "ecdad97ca3d7a3be9fe1de0e65fa7b4f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23414] Issue with network connection')"}, {"name": "tag", "value": "production"}, {"name": "tag", "value": "development"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "user-HP-250-G6-Notebook-PC"}, {"name": "thread", "value": "29410-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}